variable "region" {}
variable "stack_name" {}
variable "deployment_id" {}
variable "admin_bucket" {}
variable "data_bucket" {}
variable "local_stack_file_path" {}
variable "s3_stack_key" {}
variable "database_stack_id" {}
variable "aws_account_id" {}
